### ISSUE TITLE
white space

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/thesaints#10]
fix this :( 
![image](https://user-images.githubusercontent.com/32041993/53861818-1b79ee80-3f9a-11e9-80d5-138afc054606.png)

**Comment by suziebytes** [comment]
## RESOLVED
set the background to url


```css


/* PAGE IMAGES */
#home {
    min-height: 100vh;
    background-image: url(Photos/restroom.jpg);
    background-size: cover;
}

#about {
    min-height: 100vh;
    background-image: url(Photos/patio3.jpg);
    background-size: cover;
}

#services {
    min-height: 100vh;
    background-image: url(Photos/patio.jpg);
    background-size: cover;
}

#faq {
    min-height: 100vh;
    background-image: url(Photos/living3.jpg);
    background-size: cover;
}

#contact {
    min-height: 100vh;
    background-image: url(Photos/flooring.jpg);
    background-size: cover;
}

```
