### ISSUE TITLE
About - Container Issues 

### ISSUE THREAD

**Issue by suziebytes** [suziebytes/thesaints#5]
- can't get the icons to be centered aligned 
Tried `justify-content-end` class offered in bootstrap [(reference)](https://getbootstrap.com/docs/4.1/utilities/flex/)

- Need to figure out how to make 2nd row (bottom portion) to span 100% of the width so that the white /black background stretches 100% 

- Is there a way to specify that the border on the white part is not transparent. The white part has opacity then i added a border on top and bottom to get the black, but it is assuming transparency as well. 

_Curious to know if it might be better to try and create two color divs (one that is white and one that is black)?  This in theory sounds like it would be easier, but I think I would have issues trying to approach positioning one on top of the other directly._ 

```css
.details {
    background: white;
    opacity: .8;
    border-top: 35px solid black;
    border-bottom: 35px solid black;
    height: 200px;
}
```
Looks like this right now: 
![image](https://user-images.githubusercontent.com/32041993/53672597-18989a00-3c38-11e9-93f7-5cbad9cf800d.png)

Should look like this:
![image](https://user-images.githubusercontent.com/32041993/53672501-b17ae580-3c37-11e9-9270-5da87c4a2b9a.png)
